
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: q6
  name: q6
spec:
  ports: ~
  replicas: 1
  selector:
    matchLabels:
      app: q6
  template:
    metadata:
      labels:
        app: q6
    spec:
      containers:
        -
          image: abhihumber/final_exam:v1
          name: q6
